import { Founder, DraperUEvent, EventRegistration, Interaction, FollowUp } from '@/types';

export const INITIAL_EVENTS: DraperUEvent[] = [
  {
    id: 'evt-001',
    slug: 'founder-mafia-night-blr',
    title: 'Founder Mafia Night — Bengaluru',
    tagline: 'High-signal networking for top 1% tech founders and tier-1 angels & VCs.',
    description: 'An invite-only evening bringing together ambitious founders building in AI, SaaS, and DeepTech across India. Enjoy curated roundtables, pitches, and direct investor connections.',
    date: '2026-08-21T18:30:00+05:30',
    endDate: '2026-08-21T22:30:00+05:30',
    venue: 'Draper Startup House, Koramangala',
    city: 'Bengaluru',
    bannerUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    category: 'Founder Mafia Night',
    status: 'live',
    capacity: 150,
    registeredCount: 127,
    checkedInCount: 86,
    newFoundersCount: 34,
    existingFoundersCount: 93,
    allowWalkins: true,
  },
  {
    id: 'evt-002',
    slug: 'founder-friday-hyd',
    title: 'Founder Friday — Hyderabad',
    tagline: 'DeepTech & AI Showcase with Draper University Silicon Valley team.',
    description: 'Bi-weekly Friday gathering of Hyderabad’s fastest growing startup founders, focusing on international expansion and Silicon Valley fundraising pipelines.',
    date: '2026-08-28T17:00:00+05:30',
    endDate: '2026-08-28T21:00:00+05:30',
    venue: 'T-Hub 2.0, HITEC City',
    city: 'Hyderabad',
    bannerUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    category: 'Founder Friday',
    status: 'upcoming',
    capacity: 120,
    registeredCount: 84,
    checkedInCount: 0,
    newFoundersCount: 22,
    existingFoundersCount: 62,
    allowWalkins: true,
  },
  {
    id: 'evt-003',
    slug: 'draperu-india-demo-day-delhi',
    title: 'DraperU India Flagship Demo Day 2026',
    tagline: '20 Handpicked Startups pitching to 50+ Global Micro-VCs & Angel Funds.',
    description: 'The culmination of our 8-week accelerator cohort where selected Indian startups pitch for up to $500k in syndicate checks.',
    date: '2026-09-12T10:00:00+05:30',
    endDate: '2026-09-12T18:00:00+05:30',
    venue: 'India Habitat Centre, Lodhi Road',
    city: 'Delhi-NCR',
    bannerUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
    category: 'Demo Day',
    status: 'upcoming',
    capacity: 250,
    registeredCount: 198,
    checkedInCount: 0,
    newFoundersCount: 60,
    existingFoundersCount: 138,
    allowWalkins: false,
  },
  {
    id: 'evt-004',
    slug: 'ai-nexus-mixer-mumbai',
    title: 'AI Nexus Mixer — Mumbai',
    tagline: 'Generative AI and Enterprise Intelligence Founders Meetup.',
    description: 'A focused roundtable on monetization, GPU orchestration, and enterprise sales in the LLM era.',
    date: '2026-07-28T18:00:00+05:30',
    endDate: '2026-07-28T21:30:00+05:30',
    venue: 'WeWork Enam Sambhav, BKC',
    city: 'Mumbai',
    bannerUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80',
    category: 'Mixer',
    status: 'past',
    capacity: 100,
    registeredCount: 95,
    checkedInCount: 88,
    newFoundersCount: 29,
    existingFoundersCount: 66,
    allowWalkins: true,
  }
];

export const INITIAL_FOUNDERS: Founder[] = [
  {
    id: 'DRU-F-000124',
    name: 'Rahul Sharma',
    email: 'rahul@xyz.com',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    linkedin: 'https://linkedin.com/in/rahulsharma-xyz',
    twitter: '@rahul_xyz',
    location: 'Hyderabad, Telangana',
    designation: 'Founder & CEO',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    bio: 'Serial entrepreneur building autonomous AI agents for enterprise workflow optimization. Ex-Microsoft, IIT Madras.',
    startup: {
      name: 'XYZ Technologies',
      website: 'https://xyztechnologies.ai',
      sector: 'AI / ML',
      subSector: 'Autonomous Enterprise Agents',
      foundedYear: 2024,
      stage: 'Early Traction',
      teamSize: '6-15',
      businessModel: 'B2B',
      problem: 'Mid-market enterprises waste 35% of engineering hours on repetitive system reconciliation and schema synchronization.',
      solution: 'Self-healing AI agents that integrate into existing data stacks to automate schema migrations and workflow pipelines without human intervention.',
      pitchDeckUrl: 'https://docsend.com/view/xyz-deck-series-a'
    },
    funding: {
      type: 'Funded',
      stage: 'Seed',
      amountRaised: '$750K',
      currency: 'USD',
      investors: ['Surge Angels', 'Titan Capital', 'Hyderabad Angels'],
      currentlyFundraising: true,
      targetAmount: '$2.5M',
      lastRoundDate: '2025-11'
    },
    relationship: 'Founder program',
    isHighPriority: true,
    tags: ['AI Mafia', 'Demo Day 2026', 'Fundraising', 'Hot Lead'],
    notesCount: 4,
    createdAt: '2025-07-15T10:00:00Z',
    updatedAt: '2026-08-21T11:30:00Z'
  },
  {
    id: 'DRU-F-000125',
    name: 'Priya Reddy',
    email: 'priya@zenocare.health',
    phone: '+91 98123 45678',
    whatsapp: '+91 98123 45678',
    linkedin: 'https://linkedin.com/in/priyareddy-zeno',
    location: 'Bengaluru, Karnataka',
    designation: 'Co-Founder & CTO',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    bio: 'Biotech researcher turned founder creating AI-guided oncology diagnostic copilots for tier-2 hospitals in India.',
    startup: {
      name: 'ZenoCare AI',
      website: 'https://zenocare.health',
      sector: 'HealthTech',
      subSector: 'AI Diagnostics',
      foundedYear: 2023,
      stage: 'Growth',
      teamSize: '16-50',
      businessModel: 'B2B2C',
      problem: 'Radiologist shortage in 600+ Indian districts causes 3-week delays in early cancer detection.',
      solution: 'Edge-computed computer vision models that pre-screen digital pathology slides in under 90 seconds with 99.1% sensitivity.',
      pitchDeckUrl: 'https://docsend.com/view/zenocare-deck'
    },
    funding: {
      type: 'Funded',
      stage: 'Pre-Series A',
      amountRaised: '$1.8M',
      currency: 'USD',
      investors: ['Blume Ventures', 'HealthX Capital'],
      currentlyFundraising: true,
      targetAmount: '$5.0M',
      lastRoundDate: '2025-09'
    },
    relationship: 'Alumni',
    isHighPriority: true,
    tags: ['HealthTech Pioneer', 'Series A Target', 'Draper Cohort 3'],
    notesCount: 6,
    createdAt: '2025-03-10T09:00:00Z',
    updatedAt: '2026-08-20T16:45:00Z'
  },
  {
    id: 'DRU-F-000126',
    name: 'Arjun Kumar',
    email: 'arjun@finflux.io',
    phone: '+91 97654 32109',
    linkedin: 'https://linkedin.com/in/arjunkumar-finflux',
    location: 'Mumbai, Maharashtra',
    designation: 'Founder & CEO',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    bio: 'FinTech innovator simplifying cross-border remittances and liquidity rails for South Asian exporters.',
    startup: {
      name: 'FinFlux Global',
      website: 'https://finflux.io',
      sector: 'FinTech',
      subSector: 'Cross-Border Treasury',
      foundedYear: 2024,
      stage: 'Early Traction',
      teamSize: '6-15',
      businessModel: 'B2B',
      problem: 'Indian SME exporters lose 4-6% on FX spread and wait 5 days for cross-border reconciliation.',
      solution: 'Instant multi-currency virtual accounts and automated UPI-to-SWIFT settlements for zero markup.',
    },
    funding: {
      type: 'Funded',
      stage: 'Pre-Seed',
      amountRaised: '$400K',
      currency: 'USD',
      investors: ['100X.VC', 'Angel Investors'],
      currentlyFundraising: false,
      lastRoundDate: '2026-01'
    },
    relationship: 'Event attendee',
    isHighPriority: false,
    tags: ['FinTech', 'Cross-Border', 'Mumbai Hub'],
    notesCount: 2,
    createdAt: '2025-11-20T12:00:00Z',
    updatedAt: '2026-08-18T14:15:00Z'
  },
  {
    id: 'DRU-F-000127',
    name: 'Sneha Patel',
    email: 'sneha@agrivista.in',
    phone: '+91 99001 12233',
    linkedin: 'https://linkedin.com/in/snehapatel-agri',
    location: 'Pune, Maharashtra',
    designation: 'Founder',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    bio: 'ClimateTech & Agritech builder deploying satellite IoT for precision water conservation in sugarcane belts.',
    startup: {
      name: 'AgriVista Precision',
      website: 'https://agrivista.in',
      sector: 'ClimateTech',
      subSector: 'Agri-IoT & Satellite Vision',
      foundedYear: 2023,
      stage: 'Early Traction',
      teamSize: '6-15',
      businessModel: 'B2B',
      problem: 'Agricultural over-irrigation drains groundwater aquifers by 18% yearly across western Maharashtra.',
      solution: 'Solar-powered IoT soil moisture probes connected to satellite imagery for automated micro-drip control.',
    },
    funding: {
      type: 'Bootstrapped',
      stage: 'Bootstrapped',
      amountRaised: '₹60 Lakhs',
      currency: 'INR',
      investors: [],
      currentlyFundraising: true,
      targetAmount: '$500K',
    },
    relationship: 'Community member',
    isHighPriority: true,
    tags: ['ClimateTech', 'Bootstrapped Stars', 'Pre-Seed Ready'],
    notesCount: 3,
    createdAt: '2026-01-05T08:30:00Z',
    updatedAt: '2026-08-19T10:00:00Z'
  },
  {
    id: 'DRU-F-000128',
    name: 'Vikramaditya Rao',
    email: 'vikram@aeromind.tech',
    phone: '+91 98450 98450',
    linkedin: 'https://linkedin.com/in/vikram-aeromind',
    location: 'Bengaluru, Karnataka',
    designation: 'Founder & Chief Architect',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    bio: 'Aerospace engineer developing heavy-payload autonomous delivery UAVs for remote defense and logistics.',
    startup: {
      name: 'AeroMind Autonomous',
      website: 'https://aeromind.tech',
      sector: 'DeepTech',
      subSector: 'Autonomous Drones & Robotics',
      foundedYear: 2022,
      stage: 'Growth',
      teamSize: '16-50',
      businessModel: 'B2B',
      problem: 'Mountainous and remote cargo transport costs 14x regular freight with extreme safety risks.',
      solution: 'Hybrid-VTOL UAVs carrying 80kg payloads across 300km range under sub-zero conditions.',
    },
    funding: {
      type: 'Funded',
      stage: 'Series A',
      amountRaised: '$4.2M',
      currency: 'USD',
      investors: ['Speciale Invest', 'Kalaari Capital'],
      currentlyFundraising: false,
      lastRoundDate: '2025-06'
    },
    relationship: 'Mentor',
    isHighPriority: true,
    tags: ['DeepTech', 'Defense', 'Series A', 'Mentor'],
    notesCount: 5,
    createdAt: '2024-09-15T14:00:00Z',
    updatedAt: '2026-08-15T11:00:00Z'
  },
  {
    id: 'DRU-F-000129',
    name: 'Ananya Singhania',
    email: 'ananya@legalflow.co',
    phone: '+91 98200 11990',
    linkedin: 'https://linkedin.com/in/ananyasinghania',
    location: 'Delhi-NCR',
    designation: 'Co-Founder & CEO',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=200&q=80',
    bio: 'Ex-Shardul Amarchand lawyer building generative AI contract redlining tailored for Indian corporate jurisprudence.',
    startup: {
      name: 'LegalFlow AI',
      website: 'https://legalflow.co',
      sector: 'SaaS',
      subSector: 'LegalTech AI',
      foundedYear: 2024,
      stage: 'Early Traction',
      teamSize: '1-5',
      businessModel: 'SaaS',
      problem: 'In-house legal teams spend 40 hours reviewing 100-page vendor contracts against Indian compliance acts.',
      solution: 'Zero-data-retention LLM assistant specialized in Indian MCA, RBI, and FEMA statutory contract audit.',
    },
    funding: {
      type: 'Funded',
      stage: 'Pre-Seed',
      amountRaised: '$350K',
      currency: 'USD',
      investors: ['Antler India', 'First Cheque'],
      currentlyFundraising: true,
      targetAmount: '$1.0M',
      lastRoundDate: '2026-03'
    },
    relationship: 'Founder program',
    isHighPriority: false,
    tags: ['LegalTech', 'SaaS', 'Delhi Hub', 'Fast Growing'],
    notesCount: 1,
    createdAt: '2026-02-14T10:00:00Z',
    updatedAt: '2026-08-19T13:30:00Z'
  },
  {
    id: 'DRU-F-000130',
    name: 'Tanmay Kulkarni',
    email: 'tanmay@stackcraft.dev',
    phone: '+91 99887 76655',
    linkedin: 'https://linkedin.com/in/tanmay-kulkarni-dev',
    location: 'Bengaluru, Karnataka',
    designation: 'Founder & CEO',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    bio: 'DevTools creator building instant distributed preview environments for microservices Kubernetes clusters.',
    startup: {
      name: 'StackCraft Dev',
      website: 'https://stackcraft.dev',
      sector: 'SaaS',
      subSector: 'Developer Tooling & Cloud Infra',
      foundedYear: 2024,
      stage: 'MVP',
      teamSize: '1-5',
      businessModel: 'SaaS',
      problem: 'Developers wait 25 minutes for staging cluster spins to test microservice pull requests.',
      solution: 'Ephemeral sandbox environments created in under 3 seconds using eBPF kernel isolation.',
    },
    funding: {
      type: 'Bootstrapped',
      stage: 'Bootstrapped',
      amountRaised: 'Bootstrapped',
      investors: [],
      currentlyFundraising: true,
      targetAmount: '$600K',
    },
    relationship: 'Community member',
    isHighPriority: false,
    tags: ['DevTools', 'Open Source', 'Koramangala'],
    notesCount: 2,
    createdAt: '2026-04-10T11:00:00Z',
    updatedAt: '2026-08-21T09:15:00Z'
  }
];

export const INITIAL_REGISTRATIONS: EventRegistration[] = [
  {
    id: 'reg-001',
    eventId: 'evt-001',
    eventTitle: 'Founder Mafia Night — Bengaluru',
    founderId: 'DRU-F-000124',
    founderName: 'Rahul Sharma',
    founderEmail: 'rahul@xyz.com',
    founderPhone: '+91 98765 43210',
    founderCompany: 'XYZ Technologies',
    founderSector: 'AI / ML',
    isNewFounder: false,
    registeredAt: '2026-08-21T09:15:00+05:30',
    checkedIn: true,
    checkedInAt: '2026-08-21T18:42:00+05:30',
    source: 'QR Scan',
    notes: 'Looking to connect with Series A leads.'
  },
  {
    id: 'reg-002',
    eventId: 'evt-001',
    eventTitle: 'Founder Mafia Night — Bengaluru',
    founderId: 'DRU-F-000125',
    founderName: 'Priya Reddy',
    founderEmail: 'priya@zenocare.health',
    founderPhone: '+91 98123 45678',
    founderCompany: 'ZenoCare AI',
    founderSector: 'HealthTech',
    isNewFounder: false,
    registeredAt: '2026-08-20T14:30:00+05:30',
    checkedIn: true,
    checkedInAt: '2026-08-21T18:55:00+05:30',
    source: 'Direct Link',
    notes: 'Speaker on AI Health panel.'
  },
  {
    id: 'reg-003',
    eventId: 'evt-001',
    eventTitle: 'Founder Mafia Night — Bengaluru',
    founderId: 'DRU-F-000128',
    founderName: 'Vikramaditya Rao',
    founderEmail: 'vikram@aeromind.tech',
    founderPhone: '+91 98450 98450',
    founderCompany: 'AeroMind Autonomous',
    founderSector: 'DeepTech',
    isNewFounder: false,
    registeredAt: '2026-08-19T11:00:00+05:30',
    checkedIn: true,
    checkedInAt: '2026-08-21T19:10:00+05:30',
    source: 'QR Scan',
  },
  {
    id: 'reg-004',
    eventId: 'evt-001',
    eventTitle: 'Founder Mafia Night — Bengaluru',
    founderId: 'DRU-F-000130',
    founderName: 'Tanmay Kulkarni',
    founderEmail: 'tanmay@stackcraft.dev',
    founderPhone: '+91 99887 76655',
    founderCompany: 'StackCraft Dev',
    founderSector: 'SaaS',
    isNewFounder: true,
    registeredAt: '2026-08-21T17:15:00+05:30',
    checkedIn: false,
    source: 'QR Scan',
  },
  {
    id: 'reg-005',
    eventId: 'evt-002',
    eventTitle: 'Founder Friday — Hyderabad',
    founderId: 'DRU-F-000124',
    founderName: 'Rahul Sharma',
    founderEmail: 'rahul@xyz.com',
    founderPhone: '+91 98765 43210',
    founderCompany: 'XYZ Technologies',
    founderSector: 'AI / ML',
    isNewFounder: false,
    registeredAt: '2026-08-21T10:00:00+05:30',
    checkedIn: false,
    source: 'Direct Link',
  }
];

export const INITIAL_INTERACTIONS: Interaction[] = [
  {
    id: 'int-001',
    founderId: 'DRU-F-000124',
    type: 'event_attendance',
    title: 'Attended Founder Mafia Night',
    description: 'Checked in at Koramangala venue. Interacted with 3 institutional angel investors.',
    date: '2026-08-21T18:42:00+05:30',
    createdBy: 'Entrance QR Scanner',
    metadata: {
      eventId: 'evt-001',
      eventTitle: 'Founder Mafia Night — Bengaluru'
    }
  },
  {
    id: 'int-002',
    founderId: 'DRU-F-000124',
    type: 'event_registration',
    title: 'Registered Founder Mafia Night',
    description: 'Dynamic entrance QR registration completed via mobile portal.',
    date: '2026-08-21T09:15:00+05:30',
    createdBy: 'Automated Registration'
  },
  {
    id: 'int-003',
    founderId: 'DRU-F-000124',
    type: 'call',
    title: 'Discussed fundraising & Series A prep',
    description: '30-minute sync with Rahul on pitch deck revisions and investor intro strategy.',
    date: '2026-08-18T15:30:00+05:30',
    createdBy: 'Anshi (Community Team)'
  },
  {
    id: 'int-004',
    founderId: 'DRU-F-000124',
    type: 'investor_intro',
    title: 'Investor introduction made',
    description: 'Sent warm intro email to Matrix Partners and Draper Associates partner desk.',
    date: '2026-08-10T11:00:00+05:30',
    createdBy: 'Rahul (Founder Team)'
  },
  {
    id: 'int-005',
    founderId: 'DRU-F-000124',
    type: 'event_attendance',
    title: 'Attended Founder Friday',
    description: 'Participated in AI demo circle in Hyderabad T-Hub.',
    date: '2026-07-28T19:00:00+05:30',
    createdBy: 'Event Desk'
  },
  {
    id: 'int-006',
    founderId: 'DRU-F-000124',
    type: 'program_application',
    title: 'Registered Founder Program Cohort',
    description: 'Submitted application for DraperU Silicon Valley Global Accelerator track.',
    date: '2026-07-15T10:00:00+05:30',
    createdBy: 'DraperU Portal'
  },
  {
    id: 'int-007',
    founderId: 'DRU-F-000125',
    type: 'meeting',
    title: 'Funding Discussion & Demo Day Prep',
    description: 'Reviewed ZenoCare clinical trial metrics and Series A term sheet expectations.',
    date: '2026-08-19T16:00:00+05:30',
    createdBy: 'Anshi (Community Team)'
  }
];

export const INITIAL_FOLLOW_UPS: FollowUp[] = [
  {
    id: 'flw-001',
    founderId: 'DRU-F-000124',
    founderName: 'Rahul Sharma',
    founderCompany: 'XYZ Technologies',
    founderEmail: 'rahul@xyz.com',
    founderPhone: '+91 98765 43210',
    title: 'Follow up regarding investor introduction',
    description: 'Connect Rahul with Tim Draper Syndicate and confirm meeting schedule for next Tuesday.',
    dueDate: '2026-08-25',
    assignedTo: 'Anshi',
    status: 'upcoming',
    priority: 'high',
    eventId: 'evt-001',
    eventTitle: 'Founder Mafia Night — Bengaluru',
    createdAt: '2026-08-21T19:00:00+05:30'
  },
  {
    id: 'flw-002',
    founderId: 'DRU-F-000125',
    founderName: 'Priya Reddy',
    founderCompany: 'ZenoCare AI',
    founderEmail: 'priya@zenocare.health',
    founderPhone: '+91 98123 45678',
    title: 'Send Demo Day stage rehearsal invite',
    description: 'Lock slot for 5-minute pitch rehearsal with venture partners.',
    dueDate: '2026-08-25',
    assignedTo: 'Anshi',
    status: 'upcoming',
    priority: 'high',
    createdAt: '2026-08-20T16:45:00+05:30'
  },
  {
    id: 'flw-003',
    founderId: 'DRU-F-000126',
    founderName: 'Arjun Kumar',
    founderCompany: 'FinFlux Global',
    founderEmail: 'arjun@finflux.io',
    founderPhone: '+91 97654 32109',
    title: 'Event Invitation for Mumbai FinTech Gala',
    description: 'Send VIP pass for next month’s Draper cross-border summit.',
    dueDate: '2026-08-27',
    assignedTo: 'Rahul',
    status: 'upcoming',
    priority: 'medium',
    createdAt: '2026-08-18T14:15:00+05:30'
  },
  {
    id: 'flw-004',
    founderId: 'DRU-F-000127',
    founderName: 'Sneha Patel',
    founderCompany: 'AgriVista Precision',
    founderEmail: 'sneha@agrivista.in',
    founderPhone: '+91 99001 12233',
    title: 'Check pitch deck updates & Climate grant fit',
    description: 'Overdue follow-up to share Draper Climate grant rubric.',
    dueDate: '2026-08-19',
    assignedTo: 'Community Team',
    status: 'overdue',
    priority: 'high',
    createdAt: '2026-08-12T10:00:00+05:30'
  },
  {
    id: 'flw-005',
    founderId: 'DRU-F-000129',
    founderName: 'Ananya Singhania',
    founderCompany: 'LegalFlow AI',
    founderEmail: 'ananya@legalflow.co',
    founderPhone: '+91 98200 11990',
    title: 'Call on LegalTech customer pilot intro',
    description: 'Scheduled discussion on corporate pilot with tier-1 enterprise partner.',
    dueDate: '2026-08-21',
    assignedTo: 'Anshi',
    status: 'today',
    priority: 'high',
    createdAt: '2026-08-19T13:30:00+05:30'
  }
];
